### ISSUE TITLE
I can't change the file download folder.

### ISSUE THREAD

**Issue by EDSln** [weolar/xpchrome#2]
The default download folder is "C:\Program Files\Common Files" and cannot be changed. Clicking the "Change" button opens a non-working window. The system is Win XP SP3.

**Comment by weolar** [comment]
ok, let me see

**Comment by weolar** [comment]
I have fixed this bug, please download it again.

**Comment by EDSln** [comment]
Yes, it is now possible to change the folder. Thank You!

**Comment by mediaexplorer74** [comment]
> I have fixed this bug, please download it again.

Hello weolar. Sorry for offtopic / pinging You here.

I'm old  web-dev + classic dev-enthusiast. I still using my old winphone which has obsolete windows 10 mobile os..
I dream on some lite version of normal chrome-based browser... Idk how to explain it ) Please share some minimal c++ webbrowser project that can be transformed into winrt/uwp...

Cheers up,
MediaExplorer

**Comment by weolar** [comment]
> > I have fixed this bug, please download it again.
> 
> Hello Weolar. Are You the main dev of XPChrome / MiniBlink "engine"? Sorry for offtopic / pinging You here.
> 
> I'm old web-dev + classic dev-enthusiast. I still using my old winphone which has obsolete windows 10 mobile os.. I dream on some lite version of normal chrome-based browser... Idk how to explain it ) Please share some minimal c++ webbrowser project that can be transformed into winrt/uwp...
> 
> Cheers up, MediaExplorer

Yes, I am the author of miniblink and xpchrome, nice to meet you. I am also a fan of older systems. I really like WinXP, but I don't have WinPhone. I wonder if it can run in a virtual machine? I once ported my miniblink to NT4, so I think I should be able to port the browser to WinPhone.

**Comment by mediaexplorer74** [comment]
> > > I have fixed this bug, please download it again.
> > 
> > 
> > Hello Weolar. Are You the main dev of XPChrome / MiniBlink "engine"? Sorry for offtopic / pinging You here.
> > I'm old web-dev + classic dev-enthusiast. I still using my old winphone which has obsolete windows 10 mobile os.. I dream on some lite version of normal chrome-based browser... Idk how to explain it ) Please share some minimal c++ webbrowser project that can be transformed into winrt/uwp...
> > Cheers up, MediaExplorer
> 
> Yes, I am the author of miniblink and xpchrome, nice to meet you. I am also a fan of older systems. I really like WinXP, but I don't have WinPhone. I wonder if it can run in a virtual machine? I once ported my miniblink to NT4, so I think I should be able to port the browser to WinPhone.

Wow! Thank You very much for yours answer. Nice to meet You. You are great developer!
Yes, VS 2017 + Win 10 SDK (build 15063) gives us WinPhone emulator.
Best / have a nice time,
ME
