### ISSUE TITLE
It crashes when trying to open the Settings page

### ISSUE THREAD

**Issue by Zero3K** [weolar/xpchrome#4]
OS: Windows 7 SP1 x64

I am attaching a ZIP archive that contains the memory dumps that it automatically made.

[reports.zip](https://github.com/weolar/xpchrome/files/13378355/reports.zip)

**Comment by weolar** [comment]
use new version, i has fix it

**Comment by Zero3K** [comment]
I just tried using it with a new profile. It works. Thanks for fixing it.
